[project]
name = "pmme"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Radu", email = "raduparaian@icloud.com" }
]
requires-python = ">=3.14"
dependencies = [
    "requests>=2.34.2",
]

[project.scripts]
pmme = "pmme:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
